before:
  hooks:
  - ./set-version.sh

builds:
  - id: yor
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goarch: "386"
        goos: darwin

archives:
  - id: yor
    builds:
    - yor
    format_overrides:
      - goos: windows
        format: zip

brews:
  -
    name: yor

    repository:
      owner: bridgecrewio
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"


    commit_author:
      name: "GitHub Action"
      email: action@github.com

    homepage: "https://www.yor.io"

    description: "Extensible auto-tagger for your IaC files"
    license: "Apache-2.0"

    install: |
      bin.install "yor"

    test: |
      system "#{bin}/yor", "--help"
