name: build-goreleaser

on:
  push:
    branches:
      - release-changes
    paths-ignore:
      - 'docs/**'
      - 'INTHEWILD.md'
      - 'README.md'
      - '.github/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  formula:
    name: Update Homebrew formula
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update the Homebrew formula with latest release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-publish=false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          TEST_TAG: 0.1.85
