name: build-goreleaser

on:
  push:
    branches:
      - release-changes
    paths-ignore:
      - 'docs/**'
      - 'INTHEWILD.md'
      - 'README.md'
      - '.github/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare:
    name: Prepare
    runs-on: [ self-hosted, public, linux, x64 ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Checkout code
        uses: actions/checkout@v2
  create-release:
    runs-on: [ self-hosted, public, linux, x64 ]
    needs: prepare
    outputs:
      version: ${{ steps.version.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: release-changes
      - name: version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: release-changes
          DEFAULT_BUMP: patch
        id: version
      - name: release
        uses: actions/create-release@v1
        with:
          draft: true
          prerelease: false
          release_name: ${{ steps.version.outputs.new_tag }}
          tag_name: ${{ steps.version.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
  formula:
    name: Update Homebrew formula
    needs: create-release
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-publish=false --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GORELEASER_CURRENT_TAG: ${{ steps.version.outputs.new_tag }}
