name: Homebrew

on:
  release:
    types:
      - created

jobs:
  formula:
    name: Update Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: bridgecrewio/yor
          tap: bridgecrewio/homebrew-formulae
          formula: yor.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}